### ISSUE TITLE
Compressing TW-Vote returns an error

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#1]
Compressing [TW-Vote](https://kookma.github.io/TW-Vote/) using Uglify returns an error on one of tiddler.

This is the tiddler Uglify complains

```
/*\
keyvals.js
type: application/javascript
module-type: filteroperator

Filter operator for returning the key_°_values of a data tiddler
Note the _°_ is a separator used here for sorting purpose

\*/
(function(){
"use strict";

/*
Export our filter function
*/
exports.keyvals = function(source,operator,options) {
	var results = [];
	var sep="_°_";

	source(function(tiddler,title) {
		var data = options.wiki.getTiddlerDataCached(title);
		if(data) {
			for (var [key, value] of Object.entries(data)) {
				results.push(key+sep+value);
			}
		}

	});

	return results;
};

})();
```

Uglify complains, it cannot compress the keyval.js for line `for (var [key, value] of Object.entries(data)) {` as below

![image](https://user-images.githubusercontent.com/830394/109272203-c76f1100-7825-11eb-9f18-b72e6845e2a6.png)

Would you please have a look and let me what is the issue?

**Comment by flibbles** [comment]
Yes. That is a >=ECMA 2015 feature, which UglifyJS doesn't support. Uglify should have skipped that one file, but all the rest inside the plugin should have been compressed correctly.

There was an alternative library to UglifyJS which someone mentioned in the Google Group thread which *does* support later features. Assuming that library can be interfaced by a single method which takes a string and returns a string, then it'd be simple to swap to.

But I didn't bother since Tiddlywiki itself doesn't use ECMA 2015 features, and when plugins do so, they reduce the profile of supported browsers.

**Comment by flibbles** [comment]
Just so you know, I just pushed v1.6.0, which has an updated UglifyJS which handles a lot of newer javascript features. I *think* `for (... of ...)` is one of the features it now handles, so it won't have to skip those files anymore.

I know for sure it's able to compress the tiddlywiki/highlight plugin again.

**Comment by kookma** [comment]
Wow! Works like a charm.
I already got warnings and Erros on compressing highlight.js, katex, vote, auto-complete, ... and some other plugins
Now Uglify compresses them without error.

This is part of log 

```
i.--- Make Basic Tiddlywiki                                             
syncer-server-filesystem: Dispatching 'save' task: $:/StoryList         
uglify: Compressing: $:/boot/boot.css                                   
uglify: Compressing: $:/core                                            
uglify: Compressing: $:/plugins/flibbles/relink                         
uglify: Compressing: $:/plugins/flibbles/uglify                         
uglify: Compressing: $:/plugins/kookma/commander                        
uglify: Compressing: $:/plugins/kookma/favorites                        
uglify: Compressing: $:/plugins/kookma/kara                             
uglify: Compressing: $:/plugins/kookma/shiraz                           
uglify: Compressing: $:/plugins/kookma/trashbin                         
uglify: Compressing: $:/plugins/kookma/utility                          
uglify: Compressing: $:/plugins/kookma/vote                             
uglify: Compressing: $:/plugins/tiddlywiki/codemirror                   
uglify: Compressing: $:/plugins/tiddlywiki/codemirror-closebrackets     
uglify: Compressing: $:/plugins/tiddlywiki/codemirror-mode-css          
uglify: Compressing: $:/plugins/tiddlywiki/codemirror-search-replace    
uglify: Compressing: $:/plugins/tiddlywiki/highlight                    
.
.
```

Interesting it also compresses itself.

Thank you for all your efforts and this invaluable tool.

**Comment by flibbles** [comment]
Yep! Though it prunes 95% of itself. All that's left is the README, license, and a single module to make source mapping work.

Glad it's working out for you.
