### ISSUE TITLE
Uglify brakes the transclude editortoolbarbutton

### ISSUE THREAD

**Issue by Hanl0n** [flibbles/tw5-uglify#11]
I used uglify 1.7.0 on an empty.html. In the uglified.html pressing the transclude editortoolbarbutton gives a red screen with internal JavaScript Error:

> Internal JavaScript Error
> Well, this is embarrassing. It is recommended that you restart TiddlyWiki by refreshing your browser
> TypeError: t.paramObject.suffix is undefined

Typing the brackets and transcluding works. Only the button seams to be broken. This happens in all my uglified Wikis.

Importing $:/core/ui/EditorToolbar/transcludify from empty.html to an uglified wiki fixes the button

**Comment by flibbles** [comment]
Yep. I see it. That would break. I'll get this as soon as I have a moment. Probably tomorrow.

**Comment by flibbles** [comment]
Screw it. I fixed it now. I'm stuck at home anyway.

The attributes in `$:/core/ui/EditorToolbar/transcludify` seemed *exactly* designed to trip up uglify. It has this:
```
<$action-sendmessage
	$message="tm-edit-text-operation"
	$param="wrap-selection"
	prefix="{{"
	suffix="}}"
/>
```

Uglify likes to remove quotes wherever it can, and it does so for "{{" and "}}", which is fine, but when *they're both together in the same widget*, then it causes a problem. Should be fine now.
