### ISSUE TITLE
Uglify Removes Double Quotes in Procedure

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#15]
I uglified Shiraz plugin. The Uglify convert 

```
\procedure table-csv(tiddler:"", delimiter:",", sortType:"alphanumeric", format:"", caption:"", class:"", header:"yes", stateTiddler:"", id:"", dclass:"dblock" )
```

to

```
\procedure table-csv(tiddler delimiter:, sortType:alphanumeric format caption class header:yes stateTiddler id dclass:dblock)
```

As you see `delimiter:","` has been converted to `delimiter:,` which is not correct. The `,` is used as attribute delimiter in TiddlyWiki.

**Comment by flibbles** [comment]
You're pretty good at finding corner cases. Looks like `\function`, `\widget`, and `\procedure` process their param arguments differently than `\define`. By one single regexp character. Why not?

Just pushed 1.9.3. That should fix the problem.
