### ISSUE TITLE
uglify make transclude button error

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [flibbles/tw5-uglify#3]
![image](https://user-images.githubusercontent.com/40897360/163220757-4e7f93d1-820c-4920-ab61-0eaf79d3fa3b.png)

I also test the `offline-external-js` workflow.
uglify would cause error when it load the `tiddlywikicore-xxx.js`

**Comment by FXTD-ODYSSEY** [comment]
use 1.4,0 version fix my problem

**Comment by flibbles** [comment]
Are you saying the 1.5.2 version is broken?

Is tiddlywikicore-xxx.js a third party plugin?

**Comment by FXTD-ODYSSEY** [comment]
> Are you saying the 1.5.2 version is broken?
> 
> Is tiddlywikicore-xxx.js a third party plugin?

not third party plugin, I follow official step
https://tiddlywiki.com/#Using%20the%20external%20JavaScript%20template

**Comment by flibbles** [comment]
I believe this issue should be fixed with 1.5.3. If you're still invested in this, let me know. Otherwise, I'm closing it.
