### ISSUE TITLE
Unglify 1.5.2 Breaks TW 5.2.3

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#4]
1. I download the latest empty.html from https://tiddlywiki.com/
2. I installed the below plugins
![image](https://user-images.githubusercontent.com/830394/182409141-f2db45dd-8c8e-4a7a-a1ae-f15ef8ed0297.png)
3. I installed Uglify 1.5.2
4. Save and reload
5. Delete Uglify
6. Save and Relaod
7. Add a new Tiddler and encounter this error:
![image](https://user-images.githubusercontent.com/830394/182409572-cc5d621f-da62-47a2-a8da-128313ac737b.png)

The same procedure works with Uglify 1.5.1

**Comment by flibbles** [comment]
Any reason why you're not using the wizard to compress your tiddlywiki?

**Comment by kookma** [comment]
Is there any difference?

**Comment by flibbles** [comment]
Not in terms of this bug, but it's strange to see people still using the old, clunky way of uglifying their tiddlywikis.

**Comment by kookma** [comment]
I use a workflow based on Node.JS on my Windows machine, an script creates for me several single html file!
I will have a look to see what is the new method! The wizard!

**Comment by flibbles** [comment]
Is this automating the process of installing and uninstalling the uglify plugin? Or are you still doing that by hand?

I only ask because if there are reasons why people are still doing it the old way, I'd like to know, because no one should be doing that anymore.

**Comment by kookma** [comment]
> Is this automating the process of installing and uninstalling the uglify plugin? Or are you still doing that by hand?

Yes, it is
I use two customize folders of plugins/themes.  A package.json with `npm run build` to do the job on the fly!

**Comment by kookma** [comment]
I just tried the Wizard here: https://flibbles.github.io/tw5-uglify/uglified.html
I dragged and dropped the empty.html 5.2.3
The process is very fast but the compressed version is 5.2.1
Is it anything wrong with me?

**Comment by flibbles** [comment]
Hmm, that's because the wizard is not using the incoming version of the core like it's supposed to. That's another issue.

But that issue is alleviated (at least until the next release). And so is this one. I haven't tested it directly, but I'm pretty certain this issue should be fixed now with 1.5.3. Let me know.

**Comment by kookma** [comment]
Thanks a million!
I am happy with 1.5.1.  It compresses TW5.2.3 from 2.2MB to 1.3MB and that is absolutely amazing!
I also will use the Wizard! It is fast and simple!

Thank you for all you efforts!

**Comment by flibbles** [comment]
No worries!

-Flibbles
