### ISSUE TITLE
Uglify Remains in Index.html Using Node.js Setup

### ISSUE THREAD

**Issue by kookma** [flibbles/tw5-uglify#6]
Using the instruction is given here: https://github.com/flibbles/tw5-uglify#nodejs
when issue `tiddlywiki --build test` everything works fine and `index.html` is produced with compressed core and plugins, but I see an Empty Uglify plugin is remained in my `index.html`.

![image](https://user-images.githubusercontent.com/830394/207545587-d5dceb67-e0e3-430e-993c-307909e139e8.png)

NOTE: As it is empty, there is no overhead!

**Comment by flibbles** [comment]
This should have been fixed with 1.5.5. Can you try it with that one?

**Comment by kookma** [comment]
Thank you @flibbles 
In 1.5.5, it works as expected.

**Comment by kookma** [comment]
I am using Uglify 1.6.0 and TiddlyWiki 5.2.5 and this issue has returned!

Is it something wrong in my side?

I use a script on Node.JS with a usual tiddlywiki.info  like below

```
{
  "includeWikis": [
    "../../src"
  ],
  "config": {
    "disable-hfs": "yes"
  },
  "plugins": [
    "tiddlywiki/codemirror",
    "tiddlywiki/highlight",
	"tiddlywiki/katex",
	"TheDiveO/ThirdFlow",
	"kookma/utility",
	"flibbles/uglify"
  ],
  "build": {
    "release": [
      "--releaseplugins",
      "--releasedemowiki"
    ]
  },
  "themes": [
    "tiddlywiki/vanilla",
    "tiddlywiki/snowwhite"
  ]
}
```

**Comment by flibbles** [comment]
I'm not seeing this. I test with 5.2.5 and it works fine for me. What is the problem you're seeing?

**Comment by flibbles** [comment]
Ohh wait. Is your problem that the plugin is still there at all? Because that's by design. I thought the bug you were pointing out before was that it was empty, when it was supposed to contain the README, license, and the module which makes source mapping work.

When creating a server, Uglify can't completely remove any plugins, even itself. But the footprint it leaves is less than 1 kilobyte, and it provides the useful tools for the client to do things like signal the server to temporarily disable compression, or to sourcemap the javascript for debugging.

Is that what you're talking about?

**Comment by kookma** [comment]
Thank you @flibbles.


> When creating a server, Uglify can't completely remove any plugins, even itself.

Yes, I see Uglify is there after compressing. I expected uglify delete itself. So, this is by design.

Screenshot of produced TW after compressing:

![image](https://user-images.githubusercontent.com/830394/209711353-25d6185a-9796-4ece-8fec-22e4e89bf9bf.png)



I exported Uglify and realized it 4kB, that means it has been deleted and a trace has been remained.

Thank you

**Comment by flibbles** [comment]
If what you're generating from your server is a standalone TiddlyWiki file (such as using `--rendertiddler`, you can use the publishfilter to remove Uglify in the resulting file. The server will still utilize Uglify for compression, it just won't be in the output, which is probably what you want. You can look at the Uglify tiddlywiki.info file for an example. It uses this trick to remove the uglify-wizard from the test, as well as jasmine from the demo file.

https://github.com/flibbles/tw5-uglify/blob/82a1180c69a7c8619e671d541c20d8bd573fc3d1/tiddlywiki.info#L21

**Comment by kookma** [comment]
Much appreciated, works like a charm! ❤
